pull_request_rules:
  - name: Automatic merge for bots on main
    conditions:
      - base=main
      - label=bots
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
  - name: Automatic merge for author
    conditions:
      - author=MunchDev
      - label!=incomplete
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
